name: build

on:
  push:
    tags:
      - "v*"

jobs:
  build:
    permissions: write-all
    runs-on: ubuntu-latest
    environment: publish
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Generate Changelog
        id: changelog
        run: |
          EOF=$(dd if=/dev/urandom bs=15 count=1 status=none | base64)
          echo "CHANGELOG<<$EOF" >> $GITHUB_ENV
          git log --no-merges --pretty=tformat:%s HEAD...$(git describe --tags $(git rev-list --tags --skip=1 --max-count=1)) >> $GITHUB_ENV
          echo "$EOF" >> $GITHUB_ENV
      - uses: actions/setup-java@v3
        with:
          distribution: 'adopt'
          java-version: '17'
      - name: Build Forge
        run: bash ./gradlew forge:build
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_USER: 'ssblur'
      - name: Build Fabric
        run: bash ./gradlew fabric:build
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_USER: 'ssblur'
      - name: Build Quilt
        run: bash ./gradlew quilt:build
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_USER: 'ssblur'
      - name: Cleanup
        run: |
          rm */build/libs/scriptor-*-dev-shadow.jar
          bash -c 'for file in fabric/build/libs/*.jar; do mv "$file" "${file%.jar}-fabric.jar"; done'
          bash -c 'for file in quilt/build/libs/*.jar; do mv "$file" "${file%.jar}-quilt.jar"; done'
          bash -c 'for file in forge/build/libs/*.jar; do mv "$file" "${file%.jar}-forge.jar"; done'
      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          name: Release
          path: |
            fabric/build/libs/scriptor-*.jar
            forge/build/libs/scriptor-*.jar
            quilt/build/libs/scriptor-*.jar
      - name: "Release"
        uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: false
          files: |
            fabric/build/libs/scriptor-*.jar
            forge/build/libs/scriptor-*.jar
            quilt/build/libs/scriptor-*.jar
      - name: Extract Tag Version
        id: tag
        run: echo "version=${GITHUB_REF:11}" >> $GITHUB_OUTPUT
      - name: "Upload Quilt to CurseForge"
        uses: itsmeow/curseforge-upload@v3
        with:
          file_path: quilt/build/libs/scriptor-${{ steps.tag.outputs.version }}-quilt.jar
          game_endpoint: "minecraft"
          relations: "qsl:requiredDependency,architectury-api:requiredDependency"
          game_versions: "Minecraft 1.19:1.19.2,Java 17,Java 18,Quilt,Client,Server"
          project_id: "817436"
          token: "${{ secrets.CURSEFORGE_TOKEN }}"
          changelog: "${{ steps.changelog.outputs.CHANGELOG }}"
      - name: "Upload Fabric to CurseForge"
        uses: itsmeow/curseforge-upload@v3
        with:
          file_path: fabric/build/libs/scriptor-${{ steps.tag.outputs.version }}-fabric.jar
          game_endpoint: "minecraft"
          relations: "fabric-api:requiredDependency,architectury-api:requiredDependency"
          game_versions: "Minecraft 1.19:1.19.2,Java 17,Java 18,Fabric,Client,Server"
          project_id: "817436"
          token: "${{ secrets.CURSEFORGE_TOKEN }}"
          changelog: "${{ steps.changelog.outputs.CHANGELOG }}"
      - name: "Upload Forge to CurseForge"
        uses: itsmeow/curseforge-upload@v3
        with:
          file_path: forge/build/libs/scriptor-${{ steps.tag.outputs.version }}-forge.jar
          game_endpoint: "minecraft"
          relations: "architectury-api:requiredDependency"
          game_versions: "Minecraft 1.19:1.19.2,Java 17,Java 18,Forge,Client,Server"
          project_id: "817436"
          token: "${{ secrets.CURSEFORGE_TOKEN }}"
          changelog: "${{ steps.changelog.outputs.CHANGELOG }}"