name: publish

on:
  push:
    tags:
      - "v*"

jobs:
  build:
    permissions: write-all
    runs-on: ubuntu-latest
    environment: publish
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - id: changelog
        uses: ssblur/git-changelog-action@v1
      - uses: actions/setup-java@v3
        with:
          distribution: 'adopt'
          java-version: '17'
      - name: Sync Body
        run: bash ./gradlew quilt:modrinthSyncBody
        env:
          MODRINTH_TOKEN: ${{ secrets.MODRINTH_TOKEN }}
      - name: Publish Quilt
        run: bash ./gradlew quilt:modrinth
        env:
          MODRINTH_TOKEN: ${{ secrets.MODRINTH_TOKEN }}
          CHANGELOG: ${{ steps.changelog.outputs.changelog }}
      - name: Publish Forge
        run: bash ./gradlew forge:modrinth
        env:
          MODRINTH_TOKEN: ${{ secrets.MODRINTH_TOKEN }}
          CHANGELOG: ${{ steps.changelog.outputs.changelog }}
      - name: Publish Fabric
        run: bash ./gradlew fabric:modrinth
        env:
          MODRINTH_TOKEN: ${{ secrets.MODRINTH_TOKEN }}
          CHANGELOG: ${{ steps.changelog.outputs.changelog }}

